### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by avilde** [jurisk/evo-ts-bootcamp#2]
## Review

# Good parts
* application works flawlessly 💯 
* clean code, almost perfect & consistent code style 
* application is deployed to surge with instructions in README file
* typings and enum used properly
* clean and correct CSS

# What can be improved
* file `state.ts` is empty and not used. Should be removed
* file `App.test.tsx` is not used. Should be removed
* Buttons should have same height. After bubble sort has ended the Start/Pause button changes into finished and jumps a bit
* file `util.ts` function is too long in one line, should be split into multiple for better code readability
* if using no semicolons then it should be applied to all Typescript files including import statements

# Summary
This homework is an great template for what is considered good homework 👍🏻 
Good job, Juris!

**Comment by jurisk** [comment]
Thank you for the comments!
